name = 'Strifegame'

modules = [
    './main',
    '@rpgjs/plugin-emotion-bubbles',
    #'@rpgjs/chat',
    #'@rpgjs/title-screen',
    '@rpgjs/mobile-gui',
    '@rpgjs/default-gui',
    '@rpgjs/gamepad'
]

spritesheetDirectories= [
    'lpc-sprites'
]

[titleScreen]
    mongodb = "mongodb://localhost:27017/rpgjs"

[start]
    map = 'simplemap'
    hitbox = [32, 32]


[inputs.up]
    name = "up"
    repeat = true
    bind = ["up", "w"]

[inputs.down]
    name = "down"
    repeat = true
    bind = ["down", "s"]


[inputs.right]
    name = "right"
    repeat = true
    bind = ["right", "d"]

[inputs.left]
    name = "left"
    repeat = true
    bind = ["left", "a"]

[inputs.attack]
    name = "attack"
    repeat = true
    bind = "space"
    delay = { duration = 200 }

[inputs.skill]
    name = "skill"
    repeat = true
    bind = "k"
    delay = { duration = 200 }